version: "3"

services:
  iroha:
    image: hyperledger/iroha-docker
    expose:
      - 50051
      - 1204
    networks:
      - private
networks:
  private:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24