version: '2'

## How to run 4 nodes?
## docker-compose up
## docker-compose scale iroha=4

## How to get container's IP?
## docker inspect <container name/id> | grep IPAddress

## What should I change to run more nodes?
## command: "4" to command: "N"
## docker-compose up
## docker-compose scale iroha=N

## How to destroy created containers?
## docker-compose down

services:
  configdiscovery:
    image: warchantua/configdiscovery
    container_name: configdiscovery
    command: "4" # number of nodes (actually, 4 by default. But it is good to explicitly show)
    expose:
      - 8000

  iroha:
    image: hyperledger/iroha-docker
    depends_on: 
      - configdiscovery
    expose:
      - 1204
    # this allows any iroha container communicate with configdiscovery by name 
    links:
      - configdiscovery
    environment:
      - IROHA_HOME=/usr/local/iroha

    ## if you run configdiscovery server, use /configure-then-run.sh
    ## All options: 
    ## /configure.sh
    ## /run.sh
    ## /configure-then-run.sh
    command: /configure-then-run.sh 
