- block:
  - set_fact:
      iroha_nodes: []
      iroha_all_nodes: []

  - name: generate hostnames (no overlay)
    set_fact:
      iroha_nodes: "{{ iroha_nodes }} + [ '{{ inventory_hostname }}:{{ iroha_peer_port | int + item | int }}' ]"
    loop: "{{ range(0, replicas |int) | list }}"
    when: not custom_hostnames and not overlay_network

  - shell: "cat /dev/urandom | tr -cd [:xdigit:] | tr '[:upper:]' '[:lower:]' | head -c {{ 8 * replicas | int}}"
    register: random_hex
    when: not custom_hostnames and overlay_network

  - name: generate hostnames (overlay)
    set_fact:
      iroha_nodes: "{{ iroha_nodes }} + [ '{{ container_basename }}-{{ item }}-{{ random_hex.stdout[item|int*8:(item|int+1)*8-1] }}:{{ iroha_peer_port }}' ]"
    loop: "{{ range(0, replicas) | list }}"
    when: not custom_hostnames and overlay_network

  - name: generate hostnames (custom_hostnames)
    set_fact:
      iroha_nodes: "{{ iroha_nodes }} + [ '{% if item.split(':') | length < 2 %}{{ item }}:{{ iroha_peer_port | int + idx }}{% else %}{{ item }}{% endif %}' ]"
    when: custom_hostnames and hostnames is defined
    loop: "{{ hostnames }}"
    loop_control:
      index_var: idx

  - set_fact:
      iroha_peers_map: "{{ iroha_peers_map | default([]) }} + [ {{ {'hostname': item, 'human_hostname': 'c_' + item | regex_replace('\\.', '_') | regex_replace(':', '_'), 'peer_port': item.split(':')[1] } }} ]"
    loop: "{{ iroha_nodes }}"

  - debug:
      var: iroha_peers_map

  - set_fact:
      iroha_nodes: "{{ iroha_peers_map }}"

  - set_fact:
      iroha_all_nodes: "{{ iroha_all_nodes }} + {{ hostvars[item]['iroha_nodes'] }}"
    loop: "{{ ansible_play_hosts }}"
    run_once: yes

  - name: generate Iroha configs
    command: "./config_gen.sh -p{{ iroha_all_nodes | join(',', attribute='hostname') }} -o{{ config_local_dir }} -f"
    run_once: yes
    args:
      chdir: "{{ role_path }}/files"

  - name: make config dirs
    file:
      path: "{{ config_local_dir }}/{{ inventory_hostname }}/conf/{{ item.human_hostname }}"
      state: directory
    loop: "{{ iroha_nodes }}"

  - name: move keys
    copy:
      src: "{{ config_local_dir }}/{{ item[0].hostname }}{{ item[1] }}"
      dest: "{{ config_local_dir }}/{{ inventory_hostname }}/conf/{{ item[0].human_hostname }}"
    loop: "{{ iroha_nodes | product(['.priv', '.pub']) | list }}"

  - name: move genesis.block
    copy:
      src: "{{ config_local_dir }}/genesis.block"
      dest: "{{ config_local_dir }}/{{ inventory_hostname }}/conf/{{ item.human_hostname }}"
    loop: "{{ iroha_nodes }}"

  - name: cleanup
    file:
      path: "{{ config_local_dir }}/{{ item[0].hostname }}{{ item[1] }}"
      state: absent
    loop: "{{ iroha_nodes | product(['.priv', '.pub']) | list }}"

  - name: cleanup
    file:
      path: "{{ config_local_dir }}/genesis.block"
      state: absent
    run_once: yes
  become: no
  delegate_to: localhost
