---
- set_fact:
    iroha_namespace = "default"
  when: create_custom_namespace | default(false) | bool

- name: Create custom namespace
  command: kubectl create namespace {{ iroha_namespace }}
  ignore_errors: yes
  tags:
    - deploy
    - required

- name: Generate Iroha configs
  include: config-gen.yml
  tags:
    - config-gen

- name: Deploy Iroha
  include: deploy.yml
  tags:
    - deploy
