version: '3'

services:
  node:
    image: hyperledger/iroha-test
    ports:
      - "50051:50051"
    environment:
      - IROHA_POSTGRES_HOST=172.18.0.3
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=HelloW0rld
      - IROHA_REDIS_HOST=172.18.0.2
      - IROHA_REDIS_PORT=6379
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - redis
      - postgres
    tty: true
    volumes:
      - ccache-data:/tmp/ccache
    working_dir: /usr/local/iroha

  redis:
    image: redis:3.2.8

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
