version: '2'

services:
  iroha:
    image: hyperledger/iroha:develop
    container_name: iroha
    ports:
      - "50051:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha-postgres
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=iroha
    depends_on:
      - postgres
    tty: true
    environment:
      - KEY=node0
    volumes:
      # as configured in example/config.sample
      - /tmp/block_store
      - ./iroha/example:/opt/iroha_data
    restart: always

  postgres:
    image: postgres:9.5
    container_name: iroha-postgres
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=iroha
    expose: 
      - 5432
    restart: always
